### PR TITLE
Extend Base.Pkg.add

### PR DESCRIPTION
**Pull request by Ismael-VC**

### CODE REVIEW

**Comment by chrisvoncsefalvay** [comment]
Thanks @Ismael-VC ;)

**Comment by Ismael-VC** [comment]
You are welcome! :smile:

**Comment by Ismael-VC** [comment]
@StefanKarpinski some method like `Pkg.add(packages...)` would be nice to have in `Base`. Don´t you think?

**Comment by chrisvoncsefalvay** [comment]
@Ismael-VC What would be the comparative benefits? I'm sure there is something there, I am just not seeing it... :)

**Comment by Ismael-VC** [comment]
@chrisvoncsefalvay yo mean the benefit of having this in `Base`?

Well I think this is very useful, wanting to install several packages at once without everyone having to roll out their own `add(packages...)` method or homologous function.

I think this version will could fail to install packages if `METADATA` is updated during the process, ideally we should check if it has been modified at master and if so reissue `Pkg.update()` again IMHO.

**Comment by Ismael-VC** [comment]
I mean in Python one can do `sudo pip install x y z` in order to install `x`, `y`and `z` packages all in one go. It would be nice to give a name to our package manager and be able to use it as a command line tool also, ie:

`$ METADATA add Gadfly Arduino x y z`

Which translates to `Pkg.add("Gadfly"); Pkg.add("Arduino"); ...`

**Comment by chrisvoncsefalvay** [comment]
Ok, makes sense, @Ismael-VC. Do you want to start an issue at the main Julia repo?

**Pull request merged**
